[build]
  # Directory where Netlify should look for the build output.
  publish = "build" 
  
  # Directory where your Netlify Functions are located.
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
